language: dart
#sudo: required
dart:
  - stable
with_content_shell: true
before_install:
  - export DISPLAY=:99.0
  - ./setup_dartium.sh
  - sh -e /etc/init.d/xvfb start
script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test --integration
  - pub run dart_dev coverage --integration --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov