name: dart_dev
version: 0.0.0
dependencies:
  ansicolor: "^0.0.9"
  args: "^0.13.0"
  coverage: "^0.7.2"
  dart_style: "^0.2.0"
  path: "^1.3.6"
  test: "^0.12.0"
  yaml: "^2.1.0"
executables:
  dart_dev: